### ISSUE TITLE
Incorrect API calls

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/object-store-harvestor#30]
Let's say we have:

- cr2 file
- jpeg derivative
- yaml sidecar

The expected sequence of operation is the following:

1. Upload cr2 file` /api/v1/file/{bucket}`, record the returned id (`file1`)
2. Upload jpeg file to `/api/v1/file/{bucket}/derivative`, record the returned id (`file2`)
3. Create metadata resource (`api/v1/metadata`) and set `fileIdentifier` to `file1`, record the returned id (`metadata1`)
4. Create derivative resource (`/api/v1/derivative`), set `fileIdentifier` to `file2` and `acDerivedFrom` to `metadata1`
5. Send managed attributes for `metadata1`

**Comment by kardecom** [comment]
all in dev branch
