### ISSUE TITLE
Allow to change the uploaded filename on upload

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/object-store-harvestor#47]
There is some cases where the name of the file on disk means nothing (Image001.cr2) but the user expects the file to have a significant filename in the object-store.

We need to be able to tell the Harvestor, via the sidecar, that a file should be uploaded under a different name.

For example:
•	Image001.cr2
•	sidecar.yaml -> uploadWithFilename: newname.cr2

The Harvestor should upload the file under the name "newname.cr2" but the file should remain Image001.cr2 on the file system.

**Comment by kardecom** [comment]
Hi @dshorthouse and @cgendreau 

I will modify the code for upload the original file to the API server to make sure it picks up uploadWithFilename file name from yml file and replace original.
I'm going to change in my existing test yml file : https://github.com/AAFC-BICoE/object-store-harvestor/blob/dev/data-test/images/2021/03/07/screen_meta.yml with the following: 

from:
```
original: sample2CR2.CR2
derivative: screen_meta.jpg
```

to:
```
original: sample2CR2.CR2
uploadWithFilename: new_file_name.CR2
derivative: screen_meta.jpg
```

Please let me know if that's what you are expecting when real test sets on the cluster will be generated.

1 More question.
is uploadWithFilename going to be optional or required field in yml file?

Thank you, Dmitri

**Comment by dshorthouse** [comment]
> is uploadWithFilename going to be optional or required field in yml file?

Thanks @kardecom! This will be optional in the yml file.

**Comment by kardecom** [comment]
Great, Thank you

**Comment by dshorthouse** [comment]
@kardecom @cgendreau I updated the metadata.yml files in the test directories to include this new key.

**Comment by kardecom** [comment]
thank you
