### ISSUE TITLE
Harvest large sample of cr2/jpg assets into Object Store

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/object-store-harvestor#63]
Sidecar metadata files are now complete on the Isilon. I suggest /isilon/ottawa-rdc-htds/data_20210202 as a good sample (1457 child directories) to harvest into the present DINA demo.

**Comment by kardecom** [comment]
@dshorthouse Could you please copy files from  /isilon/ottawa-rdc-htds/data_20210202 to /isilon/ottawa-rdc/users/karpinskid/qa-demo/?
Otherwise I need an access to /isilon/ottawa-rdc-htds/data_20210202 which can be given to me by Admin, which is you or Satpal. 
Thank you, Dmitri

**Comment by dshorthouse** [comment]
Will get Satpal to coordinate permissions.
