### ISSUE TITLE
object-store-api 0.38 breaking change

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/object-store-harvestor#66]
`managedAttributeValues` is now called `managedAttributes` in object-store-api 0.38

**Comment by dshorthouse** [comment]
For what it's worth, the sidecar `metadata.yml` files have bits like this:

...stuff above...
```
managedAttributes:
  original_directory_name: dc1.2021-06-29_08-22-44_5189f8
```
...stuff below...

Am assuming there's no need to make any adjustments to the structure of these or the naming of the parent key, `managedAttributes`. It would be a significant bit of work to do so.

**Comment by cgendreau** [comment]
Fixed by https://github.com/AAFC-BICoE/object-store-harvestor/pull/67
